### ISSUE TITLE
UIScrollbar in a container prevents scrolling in parent container even when there is nothing to scroll

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#102]
If there is a parent container that has a scrollbar and there is another container in it that has a scrollbar, then even if the scrollbar in the nexted container doesn't have anything to scroll, it will prevent the one in parent from working.

The generally expected GUI behavior is that if you scroll through everything in an element, then the parent element will scroll (and I just tested it in chrome here on github).

**Comment by Ordinastie** [comment]
Fixed in the next update.
