### ISSUE TITLE
Most (all?) implementations of IScrollable will return nonsense values for offset if size >= contentSize (including NaN)

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#103]
The `NaN` value is especially problematic as it may cause strange behavior in code that doesn't expect `NaN`. For `size > contentSize` a negative value will be returned which isn't as bad as `NaN`.

The expected way would be to return zero as there is no offset in that case.

**Comment by Ordinastie** [comment]
Fixed in the next update.

**Comment by Niko-sk2x** [comment]
There is still `NaN` when `size == contentSize`
