### ISSUE TITLE
[1.11.2] Debug output?

### ISSUE THREAD

**Issue by Terpo** [Ordinastie/MalisisCore#104]
We are playing on a server<->client environment with forge 2315
and 
malisisblocks-1.11.2-5.1.0.jar
malisiscore-1.11.2-5.2.1.jar
malisisdoors-1.11.2-6.1.1.jar
malisisswitches-1.11.2-4.1.0.jar

Everytime I am visiting a player who uses a malisis door I'm getting the following output as "grey" text:
[21:12:35] [Chunk Batcher 0/INFO]: [CHAT] Registered : BlockPos{x=606, y=69, z=94}
As this block is a malisis door I think your mod is involved. I tried to find a message with "registered and found the following:
https://github.com/Ordinastie/MalisisCore/blob/1.11/src/main/java/net/malisis/core/renderer/AnimatedRenderer.java#L183

It is just a minor thing, but I wanted let you know^^

**Comment by Ordinastie** [comment]
Will be fixed in the next version.
