### ISSUE TITLE
setAlpha not being fully respected across multiple UIBackgroundContainers

### ISSUE THREAD

**Issue by Grinch** [Ordinastie/MalisisCore#106]
Attempting to set the alpha on my containers in my HUD are resulting in this: http://imgur.com/a/kDMbM

Here is a link to the HUD screen: https://github.com/AlmuraDev/Almura/blob/bleeding/src/main/java/com/almuradev/almura/client/gui/screen/ingame/hud/OriginHUD.java
Here is a link to the HUD components: https://github.com/AlmuraDev/Almura/tree/bleeding/src/main/java/com/almuradev/almura/client/gui/component/hud

**Comment by Ordinastie** [comment]
Fixed.
