### ISSUE TITLE
UITextField has very bad performance when rendering long strings

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#112]
I identified the performance issue to be in `MalisisFont.getStringWidth`. For 3000 characters string I'm getting maybe a few FPS in world customization settings, but only when the beginning of the text is shown. When the end of the text it shown, it works fine.

In vanilla it works fine.

Note: this is after disabling translation in my font by making processString return the input without any changes.

**Comment by Ordinastie** [comment]
Fixed.

**Comment by Niko-sk2x** [comment]
Any chance it could be also back ported to 1.11.2? I want to support both 1.11 and 1.12 for some time and the performance issue will only get worse as I add more convenient fig options

**Comment by Ordinastie** [comment]
Once I figure out how to do it... Egit doesn't seem to allow range cherry picking :/
I guess I'll have to pick them 1 by 1 :x
