### ISSUE TITLE
UITextField offset isn't adjusted to match cursor position after resizing

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#114]
I used `UITextField.getCursorPosition().jumpToEnd()` to jumpt to the end of the text, but it doesn't work correctly after resizing the UITextField.

<details><summary>What it should look like (click to expand):</summary><p>

![2017-07-26_00 02 02](https://user-images.githubusercontent.com/1349112/28595800-c49a554c-7195-11e7-9204-d169d21378ce.png)
</p></details>

<details><summary>After decreasing size:</summary><p>

![2017-07-26_00 02 08](https://user-images.githubusercontent.com/1349112/28595948-84328028-7196-11e7-8b26-92995157aa3c.png)
</p></details>

<details><summary>After increasing size:</summary><p>

![2017-07-26_00 02 12](https://user-images.githubusercontent.com/1349112/28595954-8a9468e6-7196-11e7-9aaa-5a26fee9d5a4.png)
</p></details>

**Comment by Ordinastie** [comment]
I'm not sure what you mean with the jumpToEnd().
But if you mean that the charOffset doesn't automatically go back so that the full width is used instead of leaving some blank, I don't really see that as an issue. And I'm not sure it's worth fixing.

**Comment by Niko-sk2x** [comment]
See the screenshot when decreasing size.. It cuts off the end of the string instead of still showing the end.

**Comment by Ordinastie** [comment]
Well yes, when you resize, the offset stays the same. Like I said, not really an issue.

**Comment by Niko-sk2x** [comment]
I guess not many people are going to actually resize the window there. I still consider it an issue but if it works as it should work...

**Comment by Ordinastie** [comment]
The question is, when you decrease the size, why should the end offset be constant instead of the start offset ? Is it because the end offset happens to match string length ?

**Comment by Niko-sk2x** [comment]
Because that's where I set the cursor position and after resize the cursor position is no longer in the visible area.

**Comment by Ordinastie** [comment]
That's because when you resize, you loose the focus of the textfield and there is no cursor anymore.

**Comment by Niko-sk2x** [comment]
I set the cursor position to the end of the string right after setting the string to match vanilla behavior in this case. Setting it seems to work even when that component is not in focus. So it still has a cursor position even if the cursor is not shown.
