### ISSUE TITLE
[MalisisDoors] Trapdoor localization doesn't work

### ISSUE THREAD

**Issue by Leo40Git** [Ordinastie/MalisisCore#115]
![2017-07-27_17 44 09](https://user-images.githubusercontent.com/7997354/28676825-60be502c-72f4-11e7-8b14-a1ed67b1f85f.png)
As you can see, both the inventory tooltip and The One Probe show "tile.null.name" instead of the correct name (which would be "Acacia Trapdoor").
Ignore the duplicate trapdoor, that one's from Quark.
FoamFix Anarchy is installed, though it doesn't mess with localization as far as I'm aware.
Using MC1.12, Forge 14.21.1.2424, MalisisCore 6.0.1, MalisisDoors 7.0.2.
**EDIT:** Whoops, this was supposed to be in MalisisDoors's repo, not here!

**Comment by Ordinastie** [comment]
Fixed in latest update.
