### ISSUE TITLE
1.12 Server Crash.

### ISSUE THREAD

**Issue by DrakFel** [Ordinastie/MalisisCore#116]
1.12 Server with latest forge crashes on launch. Client with the same mods installed launches and runs fine.

The server crashes with any 1.12 version installed (6.0.1, 6.0.2, 6.0.3 & 6.0.4).

Any fix/help would be appreciated.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  BCModPlugin (backpacks 1.12 - 3.3.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.4-1.12-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 8/20/17 9:43 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.malisis.core.block.IBlockComponent.getSubBlocks(Lnet/minecraft/block/Block;Lnet/minecraft/creativetab/CreativeTabs;Lnet/minecraft/util/NonNullList;)V
	at net.malisis.core.block.MalisisBlock.func_149666_a(MalisisBlock.java:400)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:149)
	at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:39)
	at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:65)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_224_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:733)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:216)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5900968400 bytes (5627 MB) / 8391753728 bytes (8003 MB) up to 8391753728 bytes (8003 MB)
	JVM Flags: 2 total; -Xmx8192M -Xms8192M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 123 mods loaded, 123 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443-universal.jar) 
	UCH	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443-universal.jar) 
	UCH	backpacks16840{3.3.0} [Backpacks!] (backpacks 1.12 - 3.3.0.jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	crafttweaker{4.0.4} [CraftTweaker2] (CraftTweaker2-1.12-4.0.4.jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MTLib-3.0.0.jar) 
	UCH	modtweaker{4.0.1} [Mod Tweaker] (modtweaker-4.0.1.jar) 
	UCH	jei{4.7.5.88} [Just Enough Items] (jei_1.12.1-4.7.5.88.jar) 
	UCH	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.12-1.9.4-pre-4.jar) 
	UCH	chisel{MC1.12-0.0.13.16} [Chisel] (Chisel-MC1.12-0.0.13.16.jar) 
	UCH	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCH	tconstruct{1.12-2.7.2.19} [Tinkers' Construct] (TConstruct-1.12-2.7.2.19.jar) 
	UCH	acintegration{1.5.0} [AbyssalCraft Integration] (AbyssalCraft Integration-1.12-1.5.0.jar) 
	UCH	actuallyadditions{1.12-r118} [Actually Additions] (ActuallyAdditions-1.12-r118.jar) 
	UCH	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	UCH	actuallybaubles{1.1} [Actually Baubles] (ActuallyBaubles-1.12-1.1.jar) 
	UCH	akashictome{1.2-9} [Akashic Tome] (AkashicTome-1.2-9.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.2.jar) 
	UCH	flyringbaublemod{0.3.0_1.12-306787e} [AngelRing 2 Bauble] (angelRingToBauble-1.12-0.3.0.46+306787e.jar) 
	UCH	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCH	morphtool{1.2-15} [Morph-o-Tool] (Morph-o-Tool-1.2-15.jar) 
	UCH	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UCH	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCH	autowalk{1.0} [AutoWalk Mod] (autowalk-1.12-1.0.jar) 
	UCH	base{3.0.0} [B.A.S.E] (base-1.12-3.0.0.jar) 
	UCH	bdlib{1.14.1.6} [BD Lib] (bdlib-1.14.1.6-mc1.12.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCH	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCH	bookshelf{2.0.420} [Bookshelf] (Bookshelf-1.12-2.0.0.420.jar) 
	UCH	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	brandonscore{2.3.2} [Brandon's Core] (BrandonsCore-1.12-2.3.2.129-universal.jar) 
	UCH	cavern{1.10.1} [Cavern] (Cavern_1.12-v1.10.1.jar) 
	UCH	ceramics{1.12-1.3.2} [Ceramics] (Ceramics-1.12-1.3.2.jar) 
	UCH	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCH	chesttransporter{2.8.7} [Chest Transporter] (ChestTransporter-1.12-2.8.7.jar) 
	UCH	chiselsandbits{14.6} [Chisels & Bits] (chiselsandbits-14.6.jar) 
	UCH	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCH	clockhud{1.4.0} [Clock HUD] (ClockHUD-1.12-1.4.0.jar) 
	UCH	clumps{2.0.0} [Clumps] (Clumps-3.0.0.jar) 
	UCH	cofhcore{4.3.4} [CoFH Core] (CoFHCore-1.12-4.3.4.12-universal.jar) 
	UCH	cofhworld{1.0.1} [CoFH World] (CoFHWorld-1.12-1.0.1.8-universal.jar) 
	UCH	compactmachines3{3.0.0} [Compact Machines 3] (compactmachines3-1.12.1-3.0.0-b124.jar) 
	UCH	crafttweakerjei{2.0.0} [CraftTweaker JEI Support] (CraftTweaker2-1.12-4.0.4.jar) 
	UCH	cyclicmagic{1.7.9} [Cyclic] (Cyclic-1.12-1.7.9.jar) 
	UCH	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UCH	eleccore{1.8.429} [ElecCore] (ElecCore-1.12-1.8.429.jar) 
	UCH	deepresonance{1.4.9} [DeepResonance] (deepresonance-1.12-1.4.9.jar) 
	UCH	draconicevolution{2.3.3} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.3.261-universal.jar) 
	UCH	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCH	embers{0.221} [Embers] (embers-0.221.jar) 
	UCH	endercompass{1.2.6.1} [Ender Compass] (EnderCompass-1.12-1.2.6.1.jar) 
	UCH	enderstorage{1.0} [EnderStorage] (EnderStorage-1.12-2.4.0.119-universal.jar) 
	UCH	valkyrielib{1.12-2.0.1a} [Valkyrie Lib] (valkyrielib-1.12-2.0.1a.jar) 
	UCH	environmentaltech{1.12-2.0.1a} [Environmental Tech] (environmentaltech-1.12-2.0.1a.jar) 
	UCH	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCH	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCH	fastleafdecay{v13} [Fast Leaf Decay] (FastLeafDecay-v13.jar) 
	UCH	fencejumper{1.0.0} [Fence Jumper] (fencejumper-1.12-1.0.0.jar) 
	UCH	flatbedrockx{1.4.0} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.4.0_1.12.jar) 
	UCH	flatcoloredblocks{mc1.12-6.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.4.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.4-1.12-anarchy.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCH	limelib{1.7.7} [LimeLib] (limelib-1.12-1.7.7.jar) 
	UCH	furnus{2.1.1} [Furnus] (furnus-1.12-2.1.1.jar) 
	UCH	thermalfoundation{2.3.4} [Thermal Foundation] (ThermalFoundation-1.12-2.3.4.13-universal.jar) 
	UCH	thermalexpansion{5.3.4} [Thermal Expansion] (ThermalExpansion-1.12-5.3.4.16-universal.jar) 
	UCH	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.12.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	hopperducts{1.5} [Hopper Ducts] (hopperducts-mc1.12-1.5.jar) 
	UCH	theoneprobe{1.4.17} [The One Probe] (theoneprobe-1.12-1.4.17.jar) 
	UCH	immersiveengineering{0.12-70} [Immersive Engineering] (ImmersiveEngineering-0.12-70.jar) 
	UCH	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.12-1.1.3.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCH	journeymap{1.12-5.5.0b1} [JourneyMap] (journeymap-1.12-5.5.0b1.jar) 
	UCH	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCH	lostcities{0.0.20beta2} [The Lost Cities] (lostcities-1.12-0.0.20beta2.jar) 
	UCH	malisiscore{1.12-6.0.4} [MalisisCore] (malisiscore-1.12-6.0.4.jar) 
	UCH	malisisswitches{1.12-5.0.0} [Malisis Switches] (malisisswitches-1.12-5.0.0.jar) 
	UCH	mekanism{9.4.0} [Mekanism] (Mekanism-1.12.1-9.4.0.318.jar) 
	UCH	mekanismgenerators{9.4.0} [MekanismGenerators] (MekanismGenerators-1.12.1-9.4.0.318.jar) 
	UCH	mekanismtools{9.4.0} [MekanismTools] (MekanismTools-1.12.1-9.4.0.318.jar) 
	UCH	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCH	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCH	naturescompass{1.5.0} [Nature's Compass] (NaturesCompass-1.12-1.5.0.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.4.jar) 
	UCH	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UCH	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCH	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UCH	harvestcraft{1.12c} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12c.jar) 
	UCH	plustic{6.3.1.1} [PlusTiC] (plustic-6.3.1.1.jar) 
	UCH	reborncore{3.2.5.88} [Reborn Core] (RebornCore-1.12-3.2.5.88-universal.jar) 
	UCH	quantumstorage{4.4.0} [QuantumStorage] (QuantumStorage-1.12-4.4.0.jar) 
	UCH	randomthings{4.0.5} [Random Things] (RandomThings-MC1.12.1-4.0.5.jar) 
	UCH	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCH	refinedstorage{1.5.17} [Refined Storage] (refinedstorage-1.5.17.jar) 
	UCH	rebornstorage{1.0.0} [RebornStorage] (RebornStorage-1.12-2.0.1.6.jar) 
	UCH	redstonearsenal{2.3.4} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.4.12-universal.jar) 
	UCH	refinedstorageaddons{0.1.1} [Refined Storage Addons] (refinedstorageaddons-0.1.1.jar) 
	UCH	xreliquary{1.12-1.3.4.706} [Reliquary] (Reliquary-1.12-1.3.4.706.jar) 
	UCH	rftools{6.13} [RFTools] (rftools-1.12-6.13.jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCH	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCH	roguelike{1.7.1} [Roguelike Dungeons] (RoguelikeDungeons-1.12-1.7.1.jar) 
	UCH	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCH	simplesponge{3.5} [Simple Sponge] (SimpleSponge-1.12-3.5.jar) 
	UCH	simplyenchanting{1.0.3} [Simply Enchanting] (SimplyEnchanting-1.12-1.0.3.jar) 
	UCH	tammodized{0.13.8} [TamModized] (TamModized-1.12-0.13.8.jar) 
	UCH	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCH	thermaldynamics{2.3.4} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.4.11-universal.jar) 
	UCH	topaddons{1.12-0.15.0} [TOP Addons] (topaddons-1.12-0.15.0.jar) 
	UCH	torchmaster{1.5.3.43} [TorchMaster] (torchmaster_1.12.1-1.5.3.43.jar) 
	UCH	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCH	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCH	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCH	voidcraft{0.24.4} [VoidCraft] (VoidCraft-1.12-0.24.4.jar) 
	UCH	waystones{4.0.15} [Waystones] (Waystones_1.12.1-4.0.15.jar) 
	UCH	xnet{1.4.0} [XNet] (xnet-1.12-1.4.0.jar) 
	UCH	xtones{1.12-1.0.5-8} [Xtones] (Xtones-1.12-1.0.5-8.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (backpacks 1.12 - 3.3.0.jar)
  brad16840.common.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.4-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  lumien.randomthings.asm.ClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AbyssalCraftAPI (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Biome (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Block (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Condition (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Disruption (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Energy (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Entity (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Event (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Integration (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Internal (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Item (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Necronomicon (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Recipe (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Ritual (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* AbyssalCraftAPI|Spell (1.10.0) from AbyssalCraft-1.12-1.9.4-pre-4.jar
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12-r118.jar
		* Base|API (1.0.0) from base-1.12-3.0.0.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.1.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.7.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12-0.4.5.34.jar
		* BotaniaAPI (79) from AkashicTome-1.2-9.jar
		* cavern.api (1.10.0) from Cavern_1.12-v1.10.1.jar
		* cavern.api.event (1.10.0) from Cavern_1.12-v1.10.1.jar
		* chesttransporter|api (2) from ChestTransporter-1.12-2.8.7.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12-0.0.13.16.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.0.13.16.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.6.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.12-1.4.9.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.3.261-universal.jar
		* ElecCoreAPI (1.0) from ElecCore-1.12-1.8.429.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.12-1.8.429.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-70.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-70.jar
		* jeresources|API (0.8.3.23) from JustEnoughResources-1.12-0.8.3.23.jar
		* journeymap|client-api (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b1.jar
		* journeymap|client-api-display (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b1.jar
		* journeymap|client-api-event (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b1.jar
		* journeymap|client-api-model (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b1.jar
		* journeymap|client-api-util (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b1.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.1-4.7.5.88.jar
		* mcjtylib_ng (2.4.4) from mcjtylib-1.12-2.4.4.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.1-9.4.0.318.jar
		* Open Glider|API (0.1) from OpenGlider-1.12-1.0.1.jar
		* QuarkAPI (1) from Quark-r1.2-104.jar
		* reborncoreAPI (3.2.5.88) from RebornCore-1.12-3.2.5.88-universal.jar
		* reborncoreAPI|Power (3.2.5.88) from RebornCore-1.12-3.2.5.88-universal.jar
		* reborncoreAPI|Recipe (3.2.5.88) from RebornCore-1.12-3.2.5.88-universal.jar
		* reborncoreAPI|Tile (3.2.5.88) from RebornCore-1.12-3.2.5.88-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.17.jar
		* valkyrielib.api (1.12-2.0.1a) from valkyrielib-1.12-2.0.1a.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.1.639+134fb1e.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by DrakFel** [comment]
It seems to be a problem with Crafttweaker. It launches fine with that and Modtweaker removed and they aren't really necessary for my build.

**Comment by Ordinastie** [comment]
It seems that Crafttweaker uses a method that was previously only available on the client but was recently changed.
The next update will have it fixed.
