### ISSUE TITLE
[1.12] Dedicated Server Crash

### ISSUE THREAD

**Issue by MacAttack-UK** [Ordinastie/MalisisCore#117]
Dedicated Server crashes using CraftTweaker2-1.12-4.0.4 with malisiscore-1.12-6.0.4 & malisisdoors-1.12-7.0.4. This does not happen using CraftTweaker2-1.12-4.0.3 or with just the client.

This was reproduced using a clean dedicated server install with the above mods installed. The only other mod present was jei_1.12.1-4.7.5.88

I'm unsure if this is a Crafttweaker issue or Malisis so I'm reporting to both.

Crafttweaker Log : https://pastebin.com/gr0E4HLC

- Minecraft: 1.12
- Forge: forge-1.12-14.21.1.2443
- Crafttweaker: CraftTweaker2-1.12-4.0.4
- Malisis Core : malisiscore-1.12-6.0.4
- Malisis Doors : malisisdoors-1.12-7.0.4

Crash Report : https://pastebin.com/6BSis4w8
Server Latest Log : https://pastebin.com/MTtgzvZF
Latest Log : https://pastebin.com/7P8905AG
Early Startup Log : https://pastebin.com/jGQ3g3jN

**Comment by MrDj200** [comment]
Got the Same problem here. Also only on the Server.
I saw it would be fixed in the next release ( #116  ) and I was wondering if you know a release date for that @Ordinastie ? 

-Dj

**Comment by D3nnis3n** [comment]
Would you mind giving out a hotfix release for this issue? It also refuses us to use your great door mod :/

**Comment by Ordinastie** [comment]
Sorry it took so long. The release should be out within a few days.
