### ISSUE TITLE
Mixin / ASM errors during startup (6.0.5)

### ISSUE THREAD

**Issue by Dockter** [Ordinastie/MalisisCore#120]
Hello,

Receiving the following error during MalisisCore startup phase:

* [09:20:02] [main/ERROR] [malisiscore/]: [ChunkCollisionTransformer] Method not found : net.minecraft.network.NetHandlerPlayServer:func_147345_a(Lnet/minecraft/network/play/client/CPacketPlayerDigging;)V

* [09:19:59] [main/ERROR] [malisiscore/]: [ChunkCollisionTransformer] Method not found : net.minecraft.item.ItemBlock:func_180614_a(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumHand;Lnet/minecraft/util/EnumFacing;FFF)Lnet/minecraft/util/EnumActionResult;

* [09:19:55] [main/ERROR] [malisiscore/]: [ChunkCollisionTransformer] Method not found : net.minecraft.world.World:func_184144_a(Lnet/minecraft/entity/Entity;Lnet/minecraft/util/math/AxisAlignedBB;)Ljava/util/List;

* [09:19:55] [main/ERROR] [malisiscore/]: [ChunkCollisionTransformer] Method not found : net.minecraft.world.World:func_147447_a(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;ZZZ)Lnet/minecraft/util/math/RayTraceResult;

**Comment by Ordinastie** [comment]
Migrated to mixins.
