### ISSUE TITLE
6.1.6+ Crash with Extra Utils 2 and Liteloader installed

### ISSUE THREAD

**Issue by tgstyle** [Ordinastie/MalisisCore#126]
https://gist.github.com/tgstyle/203665958710c9aa10743dd92bf37a09

Extra Utils 2 1.6.3

Server crashes with same error.

**Comment by Ordinastie** [comment]
Please post full log.

**Comment by tgstyle** [comment]
https://gist.github.com/tgstyle/ee3b1602e144a4a8a582ab540c24f9af

**Comment by Ordinastie** [comment]
Something seems to be conflicting, I just don't know what.
I'd start with FoamFix. Remove it, see if that fixes it.

**Comment by tgstyle** [comment]
I would say that could be it, but 6.0.4 works just fine. Just won't work with the later crafttweaker. I can still give it a shot though.

**Comment by tgstyle** [comment]
No go, removed foamfix and optifine. Produced the same crash.

**Comment by Ordinastie** [comment]
Apprently, it's something about Liteloader, but I wasn't able to replicate the crash.

**Comment by tgstyle** [comment]
I can confirm it involves liteloader, extrautils and malisiscore, I will see if I can figure out ways to replicate it.

**Comment by tgstyle** [comment]
I can replicate the crash every time with just those 2 mods installed with liteloader.

**Comment by tgstyle** [comment]
I did more testing
Extrautils + Liteloader = No crash
Malisiscore + Liteloader = No crash
Extrautils + Malisiscore = No crash
Extrautils + Malisiscore + Liteloader = Crash

**Comment by tgstyle** [comment]
http://develop.liteloader.com/liteloader/LiteLoader/issues/36

**Comment by tgstyle** [comment]
It could be the mixin version packaged with the snapshot of liteloader. Compiling liteloader manually includes mixin version 0.7.4 and does not crash.
