### ISSUE TITLE
Crash When Right-Clicking Door with Another Door in Main Hand

### ISSUE THREAD

**Issue by BraniyaKz** [Ordinastie/MalisisCore#130]
MC Version: 1.12.2
Forge Version: 14.23.0.2515
Malisis Doors Version: 7.1.1
Malisis Core Version: 6.1.7
Crash Report: [Click Here](https://pastebin.com/9WYdrcN2)
Description:

Malisis' mods don't seem to like it when trying to open door with another door in hand.

**Comment by Ordinastie** [comment]
I think the problem comes from Fancy Block Particles.

**Comment by BraniyaKz** [comment]
I shall post this on their thread also. It only seems to happen with one particular door, all others seem to work okay.
