### ISSUE TITLE
When quickly moving mouse cursor from enabled to disabled component (slider?), the enabled one still shows as hovered

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#133]
Steps to reproduce:
 * Create 2 sliders near each other
 * Disable one of them (but still show it)
 * Quickly move your mouse cursor from the enabled to disabled one
 * The enabled one may still show as hovered (highlighted). Repeat previous step if it isn't.

**Comment by Ordinastie** [comment]
Fixed.

**Comment by Niko-sk2x** [comment]
In which commit? (same for the other 2 fixed issues)
