### ISSUE TITLE
[1.12.2] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by LiskoSlayer63** [Ordinastie/MalisisCore#139]
Minecraft is starting fine but it crashes every time when I try to load a save. There's only **OptiFine** and **MalisisCore** & **MalisisDoors** in mods directory. I tried it without the MalisisDoors but it still crash. **I have LiteLoader installed** too but there's not any mods for it.

**Forge version**: 14.23.0.2544
**LiteLoader version**: 1.12.2-SNAPSHOT-r47E1F2F-b3-3
**MalisisCore version**: 6.1.7

I uploaded the crash log [here](https://pastebin.com/GL24DC43).

**Comment by Ordinastie** [comment]
It's an issue with Lite Loader. The author is supposed to make a new release to fix if he hasn't already (make you're using latest version).

**Comment by LiskoSlayer63** [comment]
@Ordinastie Oh, that's good to hear. I'm using their repository to automatically update always to the latest version, but apparently it's still almost two months old. Hopefully they release a fix soon. Thank you for the quick reply!

**Comment by Ordinastie** [comment]
You can bump the issue on LiteLoader repo if you want : http://develop.liteloader.com/liteloader/LiteLoader/issues/36
