### ISSUE TITLE
UIMultiLineLabel missing \n line break ability within your buildLines method.

### ISSUE THREAD

**Issue by mcsnetworks** [Ordinastie/MalisisCore#31]
At line:

https://github.com/Ordinastie/MalisisCore/blob/master/src/main/java/net/malisis/core/client/gui/component/decoration/UIMultiLineLabel.java#L138

You've specified only \r, which I assume is for Linux.  Can you please use:

String[] texts = text.toString().split("(?<=\r)\n?");

As you did in UITextField.

Thank you.

**Comment by Ordinastie** [comment]
Fixed in the next snapshot.
