### ISSUE TITLE
Feature Request:  add ability to make a button for the UIMoveHandle

### ISSUE THREAD

**Issue by mcsnetworks** [Ordinastie/MalisisCore#32]
Can you please make it so we can use a UIbutton, UIContainerBackground or an UIImage as the piece to control UIMoveHandle?

See this picture:  http://www.almuramc.com/images/almura-2-3.png

We would like to be able to click a [ ] button next to the X to move the window around instead of the icon in the upper left corner of the window.

**Comment by Ordinastie** [comment]
You would need to make that component yourself.
