### ISSUE TITLE
TexturePack Change doesn't trigger text to re-center due to font size change

### ISSUE THREAD

**Issue by mcsnetworks** [Ordinastie/MalisisCore#33]
This is still an issue.

Isn't there a method that could be called on the UIComponents to have it recalculate its width etc when  this.mc.scheduleResourcesRefresh(); is called?

From Zidane: Isn't there a forge event you could listen for and just re-run your math calculation?

**Comment by Ordinastie** [comment]
I think it's that specific GUI's job to know when that happens and rebuild itself instead of making it general.
