### ISSUE TITLE
Build number too big

### ISSUE THREAD

**Issue by Adaptivity** [Ordinastie/MalisisCore#35]
http://i.imgur.com/aVh6jrT.jpg tested on the latest version from Curse. Can it be shorter?

**Comment by Zidane** [comment]
Besides the fact that it seems to repeat itself, what does this matter (regarding the length)?

**Comment by Adaptivity** [comment]
It's just ugly :smile:

**Comment by Zidane** [comment]
I'm sure you'll live :P.

Up to Ordi though.

**Comment by Ordinastie** [comment]
That'd be nice if at least it was correct. What's right of the + should probably be removed.

**Comment by Ordinastie** [comment]
Fixed.
