### ISSUE TITLE
Feature Request - Ability to mark UITextField as not editable.

### ISSUE THREAD

**Issue by Zidane** [Ordinastie/MalisisCore#43]
While I am perfectly aware that this makes it basically a UIMultilineLabel, in my mod Guide I have a TextField that has the Guide's text that one can modify and save but if a user doesn't have permission, I want them to still be able to highlight and copy text but not change any contents. Setting the UITextField to disabled stops keystrokes but prevents highlighting and copying.

**Comment by Zidane** [comment]
I'm also aware I could just listen to TextChangeEvent and stop that (if its firing, haven't checked) but I'd rather not continue checking a permission node each time they try to...as well as I'd rather you not fire textchangeevents if we can get away with it.

Big GUI frameworks like Visual Studio have this exact functionality (I use it myself).

**Comment by Ordinastie** [comment]
Done
