### ISSUE TITLE
Chained worldgen through ChunkCollision

### ISSUE THREAD

**Issue by Player3324** [Ordinastie/MalisisCore#46]
See http://paste.ubuntu.com/10664959/

I've only had a quick look, but it seems like this mod may be responsible for loading a huge quantity of chunks, most likely unintentionally.

**Comment by Ordinastie** [comment]
I'm not sure it's entirely my fault as serveral other mods are involved and I have no issue with Vanilla worldgen.
CustomMobSpawner does a EntityLiving.getCanSpawHere() inside the world gen and I'm not convinced it should.
That said, in my process, I need to check chunks adjacent to the passed coordinates, and that's probably why it loops too much. 
Hopefully, adding  if (world.getChunkProvider().chunkExists(cx, cz)) will fix that issue.
