### ISSUE TITLE
Blinking Cursor is at the wrong position

### ISSUE THREAD

**Issue by Dockter** [Ordinastie/MalisisCore#50]
The longer you type in a text box the worse the issue becomes. What happens is that the blinking cursor graphic starts to appear before the spot your typing at.

Tested with "Almura Preferred Font.zip" texture pack / font from our public repo

http://www.almuramc.com/images/GuideError3.png

Default font works fine, which mean issue is within MalisisCore and calculating its font and string width with custom fonts.

**Comment by Dockter** [comment]
This has been confirmed to be a calculation conflict with CustomFonts and Optifine.

**Comment by Ordinastie** [comment]
I assume it's fixed. Reopen if not.
