### ISSUE TITLE
more raytrace trouble. Latest versions

### ISSUE THREAD

**Issue by Dulciphi** [Ordinastie/MalisisCore#56]
http://pastebin.com/GgqGPWw4

This is with latest versions of Special mobs and Zombie Awareness, too. I'm not sue which mod's doing what with this crash. All I know is that t the crashes started on the first night after placing a Malisis Door.

**Comment by liach** [comment]
Special mobs bug I think.

**Comment by Dulciphi** [comment]
I suspected as much as well, until I saw [this](https://github.com/TheDrunkMafia/ThaumicInfusion/issues/5). I really don't know, though. I'll bring it up with FatherToast. Thanks

**Comment by Ordinastie** [comment]
I've taken a wild guess on why and how that error could happen as it really seems impossible according to the code.
I don't think it has anything to do with special mobs unless they included some sort of multi-threading (which I doubt).
Anyway the potential fix will be available in the next update.

**Comment by Dulciphi** [comment]
I'm beginning to wonder if maybe I've mutilated something somehow, since no one else seems to be having this issue, but I just got another ray-trace crash. Same mods. Same game - this time with a vanilla zombie. Slightly different [error report](http://pastebin.com/7UsYvZA0).

**Comment by Ordinastie** [comment]
It's the same error.
But I am so deep into updating to 1.8 that I didn't have time to make a new release for 1.7 :(
[Edit :]Actually no, it's not exactly the same error, but it's also one already fixed and waiting to be release.

**Comment by Dulciphi** [comment]
:) thank you. glad to hear you're updating and staying with it too.
