### ISSUE TITLE
Console Spam related to Carpenter Blocks: "Tried to get GarageDoorTileEntity at <x>,<y>,<z>, but found TEBase instead."

### ISSUE THREAD

**Issue by starg09** [Ordinastie/MalisisCore#57]
Just wanted to report about this spam in console. Using the "Frutas Alocadas" Modpack v2.2.0 (codepack "frutas" on FTB Launcher). I have had latest version of Malisis Doors and Core for a while, but just noticed this. It happens everytime my garage door opens...

Checking on the moment, I noticed it happened the locations mentioned were of the five blocks below the actual door. Those were Carpenter Blocks, with a "Onyx Cobblestone" from GeoStrata. Removing it, and placing the cobblestone directly stopped the spamming... (Just leaving the Carpenter Blocks, with no texture, also caused the spam in console)
- The garage door in the world: http://i.imgur.com/RHBpIew.png
- The blocks mentioned in the spam: http://i.imgur.com/ZmF89jO.png
- An piece of the spam in console: http://i.imgur.com/jiMMMP4.png

**Comment by Ordinastie** [comment]
Fixed some time ago.
