### ISSUE TITLE
java.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.Stitcher.getCurrentWidth()

### ISSUE THREAD

**Issue by sblectric** [Ordinastie/MalisisCore#65]
When I install MalisisCore, this crash occurs. When I uninstall it, it goes away.
Crash report: http://pastebin.com/TD2d6cne

MalisisCore version 1.8.9-2.0.0
Forge version 11.15.1.1761

**Comment by Ordinastie** [comment]
Fixed in 1.8.9-2.0.1
