### ISSUE TITLE
1.9 crash 

### ISSUE THREAD

**Issue by RayzoRayy** [Ordinastie/MalisisCore#68]
Can't seem to launch the pack with, Malisis Core, Doors, and Adverts installed, among many other mods, also tested alone with just those 3, gives a crash with Outofboundsarray -1. Pastebin log is below.

http://pastebin.com/Fv79APmJ

**Comment by Ordinastie** [comment]
As this bug doesn't happen in dev, it's a bit hard to correct.
Here is a blind fix, can you tell me if it still happens with that jar ? : http://puu.sh/omIdt.jar

**Comment by RayzoRayy** [comment]
I will test it shortly and let you know!

**Comment by RayzoRayy** [comment]
Can confirm that this did indeed fix the issue, Malisis Doors, and Advert are now working and launching properly. They also work in game. Thank you for your hard work. :)

**Comment by Ordinastie** [comment]
Fixed in the latest version.
