### ISSUE TITLE
Server side crashes (MC 1.9)

### ISSUE THREAD

**Issue by cap10zeus** [Ordinastie/MalisisCore#69]
http://pastebin.com/DumVzEvL

**Comment by Ordinastie** [comment]
There is nothing pointing to my direction here.
Test with only Malisis mods, and if it still crashes, post the full client log.

**Comment by cap10zeus** [comment]
Tested only with Malisis mods, still got same error. Loads fine in Single player. But when thrown on server, it crashes. 
Found this on line 293:
Caused by: java.lang.RuntimeException: Attempted to load class bku for invalid side SERVER
http://pastebin.com/j0yW3iww
