### ISSUE TITLE
Add MalisisCore AT entry to FMLAT in Manifest

### ISSUE THREAD

**Issue by Zidane** [Ordinastie/MalisisCore#70]
@Ordinastie 

This is needed for people who depend on you and want to utilize FG's:

```
minecraft { 
    useDepAts = true
}
```

This reads from your manifest and applies it. Otherwise, I have to copy all your AT entries into my AT file for dev environment to work :/.

**Comment by Ordinastie** [comment]
Was done in 1.9 and backported to 1.8.9.
