### ISSUE TITLE
(1.9) Client crash when placing mod item

### ISSUE THREAD

**Issue by PlacidK** [Ordinastie/MalisisCore#71]
When placing a block reader from integrated dynamics i get this crash --> http://pastebin.com/khdb6NsA

When placing a item filter conveyor from power advantage i get this crash --> http://pastebin.com/yaRUKMwr

Both mention malisis core chunkcollision (that's why i posted the issue here first).

Integrated dynamics uses Cyclops core.

power advantage is a mod/api needed for electric and steam advantage mods.

If you think/know the other (core-)mods cause the problems i'll post the crashlogs on theyr githubs.

**Comment by Ordinastie** [comment]
It will be fixed in the next update. Thanks for the report.
