### ISSUE TITLE
Conflict with NeoTech flushable chest (1.9)

### ISSUE THREAD

**Issue by m1jordanallen** [Ordinastie/MalisisCore#72]
Hello, I have been running a 1.9 pack with no issues with the flushable chest from NeoTech for quite some time now.  I added MalisisCore/doors/switches/blocks to the pack and suddenly the chest crashes the game.  If this is something that should be reported elsewhere let me know.  I tried this in a few versions of forge including the recommended version 12.16.1.1887

http://pastebin.com/e17JAu5J

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-4.2.0.
