### ISSUE TITLE
[1.10.2] Random Crash: Tesselating block in world

### ISSUE THREAD

**Issue by SirDavidLudwig** [Ordinastie/MalisisCore#77]
Not sure what to title this issue...

Anyway, I'm running this on a server, and when I visit certain parts of my world, the client crashes.  I'm running the latest commit [8726286] on MC 1.10.2.  There's nothing in the part of my world that I would think would cause it to crash like this.  I was in the Nether for this crash when nearing a portal I haven't been to in a while, and it also seemed to crash in the Overworld when nearing a different portal.  But I have a lot of other portals around as well, so I'm not sure if they really have anything to do with it, just thought it was a coincidence that both crashes I had were near portals I haven't been to in a while...

Currently, I'm unable to join back into the server without it crashing, unless I remove the mod first.

[crash-2016-07-26_14.06.20-client.txt](https://github.com/Ordinastie/MalisisCore/files/384584/crash-2016-07-26_14.06.20-client.txt)

**Comment by Ordinastie** [comment]
Can you try without Optifine ?

**Comment by SirDavidLudwig** [comment]
Hmmmmm, it seems to work great without Optifine.  What about Optifine would be crashing it?

**Comment by Ordinastie** [comment]
It seems like it does some dumb stuff. I'll see to protect against it in a future version.

**Comment by SirDavidLudwig** [comment]
Ok cool. I went ahead and added an if statement to check if the world was null, it fixed it, but I'm not sure how safe that is.  No issues in the world though from what I can tell.

**Comment by Ordinastie** [comment]
Oh, I didn't realise you were building it yourself.
But yes, it looks like Optifine sometimes passes a null world when rendering blocks, which make no sense at all.
If a fix is to be found at all, it would probably be a null check as early as MalisisRegistry.renderBlock().

**Comment by SirDavidLudwig** [comment]
Oh yeah, I build a lot of mods myself cause I like to have the bleeding edge releases (probably not the best idea lol). I'm still somewhat new to modding, but have some years experience in programming.  I'll take your advice and add some earlier checks to get by until you put out your own proper fix lol.
