### ISSUE TITLE
[1.10.2] Server crash entering new chunks

### ISSUE THREAD

**Issue by kwpugh** [Ordinastie/MalisisCore#78]
Forge: 2029
Mods: malisisblocks-1.9.4-4.0.0.jar, malisiscore-1.9.4-4.0.2.jar, malisisdoors-1.9.4-5.0.1.jar

Server starts up fine, but when you teleport to another location, the chunk doesn't load right away, the server CPU rises to 100% and then it crashed

Crash report: http://pastebin.com/raw/mM43MYje

**Comment by Ordinastie** [comment]
Can you post the full log please ?

**Comment by kwpugh** [comment]
dml-server-latest:  https://gist.githubusercontent.com/kwpugh/f22e66295b9a247d6dce1f030c7dd3b1/raw/04a401363ea52db6911740e221102ed2b9ff1efc/malisiscore

**Comment by kwpugh** [comment]
latest.log:  https://gist.github.com/kwpugh/398521c9aa2543808e22d98b270b676c

for additional info

**Comment by Ordinastie** [comment]
That's an odd one. I don't see anything that could cause that. Does it happen when only Malisis mods are installed ?

**Comment by kwpugh** [comment]
Yes.   When I disable malisiscore and repeat the behavior, no crash.

**Comment by Ordinastie** [comment]
I meant the other way around. Only Malisis mods installed.

**Comment by kwpugh** [comment]
do you mean no other mods but malisis?  Did not try that.

**Comment by kwpugh** [comment]
Ok, so I setup a server with only malisiscore and malisisdoors.   No crashes when enter new chunks, but when entering new chunks, the mean tick time stays up around 35-45 ms.  I waited several minutes without moving to see if the tick time would go down, it does not.   When no one is on the server, the tick to is between 0-1.5 ms.

**Comment by Ordinastie** [comment]
I beleive this was fixed in latest versions.
