### ISSUE TITLE
Latest of this and Optifine aren't friends

### ISSUE THREAD

**Issue by Mach12** [Ordinastie/MalisisCore#79]
- 1.10.2
- This mod, version 4.1.1 (latest as I write this, I believe)
- Optifine 1.10.2 HD U C2 (ditto)

Crash.

[Of course I have a crash log.](https://github.com/Ordinastie/MalisisCore/files/427120/crash-2016-08-19_15.49.12-client.txt)

**Comment by Ordinastie** [comment]
Fixed in latest version.
