### ISSUE TITLE
Crash with new versions 

### ISSUE THREAD

**Issue by tacogerbil** [Ordinastie/MalisisCore#81]
Malisisdoors 1.10.2-5.1.0 and malisiscore 1.10.2-4.2.0.  forge-1.10.2-12.18.1.2094

If I revert to the previous versions all is good in the world and it loads completely... 

**My _"latest log"_ only gets this far...**
http://pasted.co/36056810

**My _fml-client-latest_** has a bit more info
http://pasted.co/e2431473

**Comment by Ordinastie** [comment]
I really don't understand... It says it can't find a method in Forge that should really be there...

Edit: does it happen reliably ? Or was it just a one time crash ?

**Comment by Ordinastie** [comment]
Should be fixed in the new version, even though the error doesn't make any sense.

**Comment by tacogerbil** [comment]
It happens like clockwork.  I spent about 2 hours testing to see if loading them first by changing their names made a difference, as well as loading them last as well as restarting a new client with fresh files.. Same every time... 
Sorry for the hassle.  Your time is sincerely appreciated :)
