### ISSUE TITLE
client crash caused by java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by NutBurger** [Ordinastie/MalisisCore#83]
malisiscore-1.10.2-4.2.1

http://pastebin.com/ft62Trxn

**Comment by NutBurger** [comment]
fixed by setting B:malisiscore.config.sortTileEntities=false in the client side config

**Comment by Ordinastie** [comment]
Does it still happen in the latest version ?

(Note: that config option can be accessed in game directly with /malisis config malisiscore)

**Comment by NutBurger** [comment]
Re-enabled the option with malisiscore-1.10.2-4.2.3 and everything is working fine

**Comment by Ordinastie** [comment]
Reopen if issue comes back.
