### ISSUE TITLE
[Forge 2094] [4.2.2] Rendering Crash

### ISSUE THREAD

**Issue by Hastling** [Ordinastie/MalisisCore#84]
The crash occurs if I even glance in the direction of any doors, and yes I'm using the latest version of Java/Optifine/Nvidia Drivers. If any extra information is needed please let me know. http://pastebin.com/KW9vFLNu

**Comment by Ordinastie** [comment]
Carriage Doors, Medieval Doors and Vertical Hatch are bugged. Currently working on released the fix.
