### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by ZiggyAdventures** [Ordinastie/MalisisCore#85]
MalisisCore malisiscore-1.1.0.2-4.2.3.jar
MalisisDoors malisisdoors-1.10.2-5.1.2.jar
In modpack All the Mods v1.33

Constant console spam, multiple reports, does not effect everyone.
Log File: https://pastebin.ubuntu.com/23276585/

Screenshots of spam: 
https://images-na.curseapp.net/714b771e-cbc3-4a0c-bff3-aabd1508931d/tracefail.jpeg
https://images-na.curseapp.net/95eb9c24-8036-4ab4-9412-b9935d9842c3/Image.png

**Comment by Ordinastie** [comment]
Last version silences the spam.
