### ISSUE TITLE
Console messages: "Chunk" and "Saving -1/0"

### ISSUE THREAD

**Issue by Ricket** [Ordinastie/MalisisCore#86]
I am seeing these two messages in the console, fairly frequently (roughly one every minute or two; the "Saving" one is more frequent)

```
[21:54:00] [Server thread/INFO] [malisiscore]: Saving -1/0
[21:59:15] [Server thread/INFO] [malisiscore]: Chunk
```

malisiscore-1.10.2-4.2.6 (part of All the Mods 1.38b)

**Comment by Ordinastie** [comment]
Already fixed in 1.10.2-4.2.7.
