### ISSUE TITLE
Crash, Game Won't Start

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisCore#87]
crashes after the latest update of malisis core.
[crash-2017-02-16_15.02.18-client.txt](https://github.com/Ordinastie/MalisisCore/files/779989/crash-2017-02-16_15.02.18-client.txt)

all information can be found in the crash log.

**Comment by Ordinastie** [comment]
Please check for new versions of the mods depending on MalisisCore before posting issues :)
There is a new version of MalisisDoors that came with MalisisCore.
