### ISSUE TITLE
Optifine D7 and MalisisCore / Door crash in 1.10.2

### ISSUE THREAD

**Issue by BakermanLP** [Ordinastie/MalisisCore#88]
Here is the crash report of this issue:
http://pastebin.com/trnU4V9S

Only changing Optifine from D7 to D6 fixes the problem. I don't know, if this is an issue with MalisisCore or MalisisDoor.

Installed versions:
- malisisadvert-1.10.2-4.2.0.jar
- malisiscore-1.10.2-4.3.0.jar
- malisisdoors-1.10.2-5.2.0.jar
- OptiFine_1.10.2_HD_U_D7.jar
... and other

Michael (aka BakermanLP)

**Comment by Ordinastie** [comment]
Fixed in MalisisCore 1.10.2-4.4.0.

**Comment by BakermanLP** [comment]
Thank you!
