### ISSUE TITLE
Crashing in 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [Ordinastie/MalisisCore#91]
I'm not sure why, but ever since I added MalisisCore, MalisisSwitches, and MalisisDoors, I keep on getting a crash log like this: [crash-2017-04-17_18.53.48-client.txt](https://github.com/Ordinastie/MalisisCore/files/926930/crash-2017-04-17_18.53.48-client.txt) whenever I open up my inventory with a custom door I created inside. I thought the Mult-Hotbar mod was the problem but it seems to be something else internal within the Malisis mods.. For each Malisis mod, I'm using the versions for 1.11.2. The versions are pasted in my crash log

**Comment by Ordinastie** [comment]
Please provide full log.

**Comment by NovaViper** [comment]
Sorry, I thought the default one gave all of the details!
https://gist.githubusercontent.com/NovaViper/280e2980a40fe21bd543425cc90bc18a/raw/f8d5af82a5d4694ac5faa4ef33e37af349a7664a/fml-client-1.log

**Comment by Ordinastie** [comment]
I don't see anything pointing to any Malisis mod causing the crash. However, there is a massive amount of errors caused by MineTweaker. Can you check if it still happen without that mod ?
Also, you said that there is no crash if multi hotbar is not installed, maybe it's something they do.

**Comment by NovaViper** [comment]
It's not MineTweaker.. here's another crash log

https://gist.github.com/NovaViper/e82675e47532aa86720d556e1ed26f28

The crashing only occurs when I add in any of the Malisis mods. I also notice this happens whenever I try to hover my mouse over one of the custom doors

**Comment by NovaViper** [comment]
Uh... I'm not sure what could be causing the crash, I completely removed the mods I had and added them back in (with Mailasis mods in first) one by one to see if they cause the crash.. But the crash doesn't seem to be occurring so far

**Comment by NovaViper** [comment]
Ah ha! I found out it was MineTweaker/CraftTweaker! https://gist.github.com/NovaViper/bf83517c4586866b815c302deb5cc7ab

I am reporting to the developers of MineTweaker now!

**Comment by NovaViper** [comment]
Hey, I notice something strange that happens between Crafting Tweaks and this mod. The crash only occurs whenever I use items (such as a water bucket) in creating the custom doors, where as it doesn't occur with blocks. And it also says "Air" as being used in Hylwa instead of water (but it displays the block's info whenever I use an acutal block)

**Comment by Ordinastie** [comment]
As I'm using other block infos and textures for Custom Doors, I can't guarantee it will work if said blocks do something more complex (or simply different) than vanilla blocks.

**Comment by NovaViper** [comment]
What about items? It only crashes whenever I use bucket items (water, lava, etc)

**Comment by Ordinastie** [comment]
I can't possibly know without a log.

**Comment by NovaViper** [comment]
The only log that displays the error is the one I posted in my first post

**Comment by NovaViper** [comment]
Here's another log: https://gist.github.com/NovaViper/bf83517c4586866b815c302deb5cc7ab

Instance with water buckets
https://gist.github.com/NovaViper/c7a205c3eb09e4b8d9c9fcfb62e088b8
![doorinfo](https://cloud.githubusercontent.com/assets/7191115/25140514/3dc9ffc0-2426-11e7-9e27-76e5185e161a.png)

Instance with Blue wool
![untitled](https://cloud.githubusercontent.com/assets/7191115/25282352/d2e484da-2675-11e7-8547-a48b09dc2092.png)

**Comment by Ordinastie** [comment]
Again, that's Minetweaker crashing here, when trying to display the tooltip for an item.

**Comment by NovaViper** [comment]
I know but the devs say it's something with the doors when they are being created as Hylwa says it's air isntead of water

**Comment by Ordinastie** [comment]
It's because door displays the tooltip for the block used as material. But the water block doesn't have an associated item.

**Comment by NovaViper** [comment]
Oh.. that could be the main issue that Crafting Tweaks is having to deal with
