### ISSUE TITLE
Is there a way to give a texture to Custom Door in NEI?

### ISSUE THREAD

**Issue by lllMohandarlll** [Ordinastie/MalisisCore#92]
Hello, I've noticed this thing, since its nature, Custom Door can have multiple outputs determinated by tags, but, isn't there a way to give a base texture to the base item (with no tags) so it will be visible (more visible) on NEI?

**Comment by Ordinastie** [comment]
With no tag, it should render using wood and glass by default.
(Also, wrong repo).
