### ISSUE TITLE
Another crash in 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [Ordinastie/MalisisCore#93]
Ok.. I think many of the mods I'm using doesn't seem to take well to any of the Malisis Mods ._.
I'm getting yet another crash whenever I try to change my shaders, but the crash ONLY happens when I have the Malsis Mods and Doggy Talents together.

The crash looks like this: https://gist.github.com/NovaViper/d8bb02d9d658c90376a742ff8b767007

**Comment by NovaViper** [comment]
I've reported this to the Doggy Talents developer aswell in ProPercivalalb/DoggyTalents/issues/26

**Comment by Ordinastie** [comment]
Nothing to do with any of my mods here.
