### ISSUE TITLE
MC1.11.2 Cascading WorldGen Lag

### ISSUE THREAD

**Issue by sandalle** [Ordinastie/MalisisCore#94]
In Minecraft 1.11.2 with Forge, I see these errors in the log
`[12:13:24] [Server thread/WARN] [FML]: MalisisCore loaded a new chunk (-20, 43  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`

mezz fixed a similar issue in Actually Additions with Ellpeck/ActuallyAdditions#690 , if that helps.

Mods:
* forge-1.11.2-13.20.0.2284
* malisiscore-1.11.2-5.1.1

**Comment by Endmateria** [comment]
Same problem.  Lots of hits in my server log for cascading worldgen lag.
Malisiscore 1.11.2 5.1.1.
Malisisblocks 1.11.2 5.1.0
Malisisdoors 1.11.2. 6.1.0
Malisisswitches 1.11.2 4.1.0
Forge 2294

A lot of mods are having a problem with this... here's a thread with all kinds of details on how to fix. https://github.com/Vazkii/Quark/issues/412

**Comment by Ordinastie** [comment]
Well, there is no worldgen in my mod, so I there is nothing I can do about it.
