### ISSUE TITLE
[1.11.2] with BetterFonts, UIs don't use font specified by BF

### ISSUE THREAD

**Issue by bluebear94** [Ordinastie/MalisisCore#95]
[BetterFonts](https://mods.curse.com/mc-mods/minecraft/243639-truetype-font-replacement) is a mod that allows Minecraft to use a TrueType or OpenType font rather than Minecraft's built-in font.

While using [a mod](https://github.com/OpenCubicChunks/CubicChunks) depending on MalisisCore, I noticed that the UI used the built-in font from Minecraft, rather than the TrueType font used by the rest of the game with BetterFonts.

**Comment by Ordinastie** [comment]
Unfortunately, MalisisCore guis don't use default Minecraft rendering, so I can't automatically use BetterFonts font directly.
I might allow the choice of default font for MalisisCore guis in the future, but it's not really high on the priority list.
