### ISSUE TITLE
Could not autoload net.malisis.core.renderer.icon.Icon

### ISSUE THREAD

**Issue by EmanYm** [Ordinastie/MalisisCore#97]
[Here](https://hastebin.com/wonalesapo.swift) is the console error during server start up.

SpongeForge 6.1.0-Build2378
MinecraftForge 13.20.0.2315
MalisisCore 5.2.0

I can attach fml-server-latest.log if you need it.

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
