### ISSUE TITLE
UISelect will remove any selection when changing option with mouse wheel up past available options and SelectEvent will give null new value

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#98]
As said in the title.

When the list is not expanded, and I use mouse wheel to select items, scrolling up past available options will remove selection. And the SelectEvent new option will be null.

Most of the time when there are options provided it doesn't make sense for the user to be able to select nothing. If this is a feature, this should be at least opt-out (or, even better, opt-in)

**Comment by Ordinastie** [comment]
Will be fixed in next update.
