### ISSUE TITLE
UISlider won't work if width is inherited

### ISSUE THREAD

**Issue by Niko-sk2x** [Ordinastie/MalisisCore#99]
`slideTo(x)` uses the width field directly, which will be zero. So it obviously won't work correctly.

**Comment by Niko-sk2x** [comment]
Similar issue is likely to happen in any other class that uses width field directly instead og `getWidth`, ones I found:
 * `UIProgressBar#drawBackground` and  `UIProgressBar#drawForeground` 
 * `UIButton#drawForeground`
 * `UISelect#drawForeground`
 * `UISlider#drawForeground`

**Comment by Ordinastie** [comment]
Fixed in the next update.
